using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SmallFarm.Data.Entities;

namespace SmallFarm.Data.Configurations
{
    internal class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.HasData(SeedCities());
        }

        private static List<City> SeedCities()
        {
            List<City> list = new List<City>();
            var allCities = new List<string>()
            {
                "Ablanitsa",
                "Aheloy",
                "Aksakovo",
                "Aldomirovtsi",
                "Aleksandrovo",
                "Asenovgrad",
                "Aydemir",
                "Aytos",
                "Balgarovo",
                "Banitsa",
                "Bankya",
                "Banya",
                "Basarbovo",
                "Bata",
                "Batanovtsi",
                "Belogradets",
                "Beloslav",
                "Benkovski",
                "Bistritsa",
                "Bistritsa",
                "Blagoevgrad",
                "Boboshevo",
                "Borovo",
                "Borovo",
                "Botevgrad",
                "Bozhurishte",
                "Bregovo",
                "Brestovitsa",
                "Buhovo",
                "Bukovlak",
                "Burgas",
                "Busmantsi",
                "Byal Izvor",
                "Byala",
                "Chepintsi",
                "Chernogorovo",
                "Cherven Breg",
                "Chervena Voda",
                "Debelets",
                "Devin",
                "Devnya",
                "Dimitrovgrad",
                "Divotino",
                "Dobri Dyal",
                "Dobrich",
                "Dobromir",
                "Dobroslavtsi",
                "Dolen",
                "Dolna Banya",
                "Dolna Oryahovitsa",
                "Dolni Bogrov",
                "Draganovo",
                "Dragichevo",
                "Dupnitsa",
                "Dzherman",
                "Dzhulyunitsa",
                "Elin Pelin",
                "Etropole",
                "Ezerovo",
                "Gabrovnitsa",
                "Gabrovo",
                "Galabets",
                "German",
                "Glavinitsa",
                "Glozhene",
                "Gluhar",
                "Gorna Oryahovitsa",
                "Gorni Bogrov",
                "Gorski Izvor",
                "Gotse Delchev",
                "Gradina",
                "Graf Ignatievo",
                "Grivitsa",
                "Gulyantsi",
                "Gurkovo",
                "Gyulyovtsa",
                "Hadzhievo",
                "Haskovo",
                "Ignatievo",
                "Isperih",
                "Ivaylo",
                "Izvorsko",
                "Kableshkovo",
                "Kadievo",
                "Kalekovets",
                "Kalipetrovo",
                "Kalofer",
                "Kamenar",
                "Karabunar",
                "Karageorgievo",
                "Karapelit",
                "Kardzhali",
                "Karlovo",
                "Kazanlak",
                "Kazichene",
                "Kermen",
                "Kilifarevo",
                "Kladnitsa",
                "Kokalyane",
                "Konstantinovo",
                "Kosharitsa",
                "Kostandovo",
                "Kostievo",
                "Kostinbrod",
                "Koynare",
                "Kozloduy",
                "Kran",
                "Krastava",
                "Kraynitsi",
                "Krepost",
                "Krichim",
                "Krivina",
                "Krushare",
                "Kukorevo",
                "Kurtovo Konare",
                "Kyustendil",
                "Lesnovo",
                "Lom",
                "Lovech",
                "Lozen",
                "Lyaskovets",
                "Lyuben Karavelovo",
                "Madan",
                "Maglen",
                "Malevo",
                "Malo Konare",
                "Marchaevo",
                "Marinka",
                "Marten",
                "Merichleri",
                "Mirovyane",
                "Mokrishte",
                "Montana",
                "Mortagonovo",
                "Negovan",
                "Nikolaevo",
                "Nikolovo",
                "Novi Pazar",
                "Novo Selo",
                "Obzor",
                "Ognyanovo",
                "Omurtag",
                "Opalchensko",
                "Orizare",
                "Ostrovo",
                "Panagyurishte",
                "Pancharevo",
                "Parvenets",
                "Parvomaytsi",
                "Patalenitsa",
                "Pazardzhik",
                "Pernik",
                "Perushtitsa",
                "Peshtera",
                "Petarch",
                "Petrich",
                "Pisarevo",
                "Planinitsa",
                "Pleven",
                "Plovdiv",
                "Polikrayshte",
                "Pomorie",
                "Prosenik",
                "Provadia",
                "Rakitovo",
                "Rakovski",
                "Rakovski",
                "Ravda",
                "Ravnets",
                "Razgrad",
                "Razhitsa",
                "Razlog",
                "Resen",
                "Rogosh",
                "Rudartsi",
                "Rudozem",
                "Ruen",
                "Ruse",
                "Sadovo",
                "Saedinenie",
                "Samoranovo",
                "Sandrovo",
                "Sapareva Banya",
                "Saraya",
                "Sarnitsa",
                "Seliminovo",
                "Semerdzhievo",
                "Septemvri",
                "Shipka",
                "Shumen",
                "Silistra",
                "Sinitovo",
                "Skutare",
                "Slavyanovo",
                "Sliven",
                "Slivnitsa",
                "Slokoshtitsa",
                "Smolyan",
                "Snyagovo",
                "Sofia",
                "Sopot",
                "Sotirya",
                "Stamboliyski",
                "Stara Zagora",
                "Startsevo",
                "Stefanovo",
                "Stozher",
                "Stratsin",
                "Studena",
                "Suvorovo",
                "Sveti Vlas",
                "Svetovrachane",
                "Svishtov",
                "Tankovo",
                "Targovishte",
                "Topolchane",
                "Topoli",
                "Tranak",
                "Trivoditsi",
                "Trud",
                "Tsaratsovo",
                "Tsarev Brod",
                "Uzundzhovo",
                "Vaglen",
                "Vaklinovo",
                "Valkosel",
                "Varbitsa",
                "Varbitsa",
                "Vardun",
                "Varna",
                "Varshets",
                "Veliki Preslav",
                "Veliko Tarnovo",
                "Velingrad",
                "Veselinovo",
                "Vetovo",
                "Vetren",
                "Vidin",
                "Vinitsa",
                "Vinogradets",
                "Vladaya",
                "Voluyak",
                "Voysil",
                "Voyvodinovo",
                "Voyvodovo",
                "Vratsa",
                "Vresovo",
                "Yabalchevo",
                "Yabalkovo",
                "Yahinovo",
                "Yambol",
                "Zaychar",
                "Zheleznitsa",
                "Zlatograd",
                "Zvezditsa",
            };

            int id = 0;
            foreach (var city in allCities)
            {
                id++;
                list.Add(new City(){Id = id, Name = city});
            }

            return list;
        }
    }
}
